// <auto-generated />
namespace TestTask_TI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dm));
        
        string IMigrationMetadata.Id
        {
            get { return "201909151539288_dm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
